import type { MaintenanceCategory } from "@prisma/client";

export type MaintenanceTemplateSeed = {
  slug: string;
  category: MaintenanceCategory;
  nameEn: string;
  nameDe: string;
  descriptionEn: string;
  descriptionDe: string;
  defaultIntervalKm: number | null;
  defaultIntervalMonths: number | null;
  defaultCostCentsMin: number;
  defaultCostCentsMax: number;
  sortOrder: number;
};

/** Intervals based on common European OEM recommendations (VAG, ADAC, TÜV). */
export const MAINTENANCE_TEMPLATE_SEEDS: MaintenanceTemplateSeed[] = [
  {
    slug: "oil_change",
    category: "ENGINE",
    nameEn: "Engine oil & filter",
    nameDe: "Motoröl & Ölfilter",
    descriptionEn: "Replace engine oil and oil filter. Typical: every 15,000 km or 12 months.",
    descriptionDe: "Motoröl und Ölfilter wechseln. Typisch: alle 15.000 km oder 12 Monate.",
    defaultIntervalKm: 15000,
    defaultIntervalMonths: 12,
    defaultCostCentsMin: 12000,
    defaultCostCentsMax: 22000,
    sortOrder: 10,
  },
  {
    slug: "air_filter",
    category: "FILTERS",
    nameEn: "Engine air filter",
    nameDe: "Luftfilter",
    descriptionEn: "Replace intake air filter. Typical: every 30,000 km or 24 months.",
    descriptionDe: "Motorluftfilter wechseln. Typisch: alle 30.000 km oder 24 Monate.",
    defaultIntervalKm: 30000,
    defaultIntervalMonths: 24,
    defaultCostCentsMin: 2500,
    defaultCostCentsMax: 5500,
    sortOrder: 20,
  },
  {
    slug: "cabin_filter",
    category: "FILTERS",
    nameEn: "Cabin / pollen filter",
    nameDe: "Innenraum- / Pollenfilter",
    descriptionEn: "Replace cabin air filter. Typical: every 15,000 km or 12 months.",
    descriptionDe: "Innenraumfilter wechseln. Typisch: alle 15.000 km oder 12 Monate.",
    defaultIntervalKm: 15000,
    defaultIntervalMonths: 12,
    defaultCostCentsMin: 3000,
    defaultCostCentsMax: 6500,
    sortOrder: 30,
  },
  {
    slug: "fuel_filter",
    category: "FILTERS",
    nameEn: "Fuel filter (diesel)",
    nameDe: "Kraftstofffilter (Diesel)",
    descriptionEn: "Replace diesel fuel filter. Typical: every 30,000 km or 24 months.",
    descriptionDe: "Kraftstofffilter wechseln. Typisch: alle 30.000 km oder 24 Monate.",
    defaultIntervalKm: 30000,
    defaultIntervalMonths: 24,
    defaultCostCentsMin: 8000,
    defaultCostCentsMax: 18000,
    sortOrder: 40,
  },
  {
    slug: "brake_fluid",
    category: "FLUIDS",
    nameEn: "Brake fluid",
    nameDe: "Bremsflüssigkeit",
    descriptionEn: "Replace brake fluid (DOT 4). Required every 24 months per most OEM specs.",
    descriptionDe: "Bremsflüssigkeit wechseln (DOT 4). Herstellerangabe meist alle 24 Monate.",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    defaultCostCentsMin: 6000,
    defaultCostCentsMax: 12000,
    sortOrder: 50,
  },
  {
    slug: "coolant",
    category: "FLUIDS",
    nameEn: "Coolant / antifreeze",
    nameDe: "Kühlmittel / Frostschutz",
    descriptionEn: "Replace coolant. Typical: every 60,000 km or 5 years.",
    descriptionDe: "Kühlmittel wechseln. Typisch: alle 60.000 km oder 5 Jahre.",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 60,
    defaultCostCentsMin: 8000,
    defaultCostCentsMax: 18000,
    sortOrder: 60,
  },
  {
    slug: "transmission_fluid",
    category: "FLUIDS",
    nameEn: "Transmission fluid",
    nameDe: "Getriebeöl",
    descriptionEn: "Replace automatic/manual gearbox oil. Typical: every 60,000 km.",
    descriptionDe: "Getriebeöl wechseln. Typisch: alle 60.000 km.",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    defaultCostCentsMin: 15000,
    defaultCostCentsMax: 35000,
    sortOrder: 70,
  },
  {
    slug: "spark_plugs",
    category: "ENGINE",
    nameEn: "Spark plugs",
    nameDe: "Zündkerzen",
    descriptionEn: "Replace spark plugs (petrol engines). Typical: every 60,000 km.",
    descriptionDe: "Zündkerzen wechseln (Benziner). Typisch: alle 60.000 km.",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    defaultCostCentsMin: 12000,
    defaultCostCentsMax: 35000,
    sortOrder: 80,
  },
  {
    slug: "timing_belt",
    category: "ENGINE",
    nameEn: "Timing belt kit",
    nameDe: "Zahnriemen / Steuerkette",
    descriptionEn: "Replace timing belt and tensioners where applicable. Typical: 120,000 km or 5 years.",
    descriptionDe: "Zahnriemen mit Spanner wechseln (falls zutreffend). Typisch: 120.000 km oder 5 Jahre.",
    defaultIntervalKm: 120000,
    defaultIntervalMonths: 60,
    defaultCostCentsMin: 45000,
    defaultCostCentsMax: 120000,
    sortOrder: 90,
  },
  {
    slug: "brake_pads",
    category: "BRAKES",
    nameEn: "Brake pads inspection",
    nameDe: "Bremsbeläge prüfen",
    descriptionEn: "Inspect brake pads; replace typically every 40,000–60,000 km.",
    descriptionDe: "Bremsbeläge prüfen; Wechsel typisch alle 40.000–60.000 km.",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: 24,
    defaultCostCentsMin: 18000,
    defaultCostCentsMax: 45000,
    sortOrder: 100,
  },
  {
    slug: "brake_discs",
    category: "BRAKES",
    nameEn: "Brake discs",
    nameDe: "Bremsscheiben",
    descriptionEn: "Inspect or replace brake discs. Typical: every 80,000 km.",
    descriptionDe: "Bremsscheiben prüfen oder wechseln. Typisch: alle 80.000 km.",
    defaultIntervalKm: 80000,
    defaultIntervalMonths: 48,
    defaultCostCentsMin: 25000,
    defaultCostCentsMax: 60000,
    sortOrder: 110,
  },
  {
    slug: "tire_rotation",
    category: "TIRES",
    nameEn: "Tire rotation & pressure",
    nameDe: "Reifenwechsel / Rotation",
    descriptionEn: "Rotate tires and check pressure. Typical: every 10,000 km or 6 months.",
    descriptionDe: "Reifen rotieren und Luftdruck prüfen. Typisch: alle 10.000 km oder 6 Monate.",
    defaultIntervalKm: 10000,
    defaultIntervalMonths: 6,
    defaultCostCentsMin: 2000,
    defaultCostCentsMax: 8000,
    sortOrder: 120,
  },
  {
    slug: "tire_change_seasonal",
    category: "TIRES",
    nameEn: "Seasonal tire change",
    nameDe: "Saisonaler Reifenwechsel",
    descriptionEn: "Swap summer/winter tires. Typical: every 6 months (Oct/Apr in DE).",
    descriptionDe: "Sommer-/Winterreifen wechseln. Typisch: alle 6 Monate (Okt/Apr).",
    defaultIntervalKm: null,
    defaultIntervalMonths: 6,
    defaultCostCentsMin: 4000,
    defaultCostCentsMax: 12000,
    sortOrder: 130,
  },
  {
    slug: "hu_inspection",
    category: "INSPECTION",
    nameEn: "General inspection (HU/TÜV)",
    nameDe: "Hauptuntersuchung (HU/TÜV)",
    descriptionEn: "Mandatory roadworthiness inspection in Germany. Every 24 months (new cars: 36, then 24).",
    descriptionDe: "Gesetzliche Hauptuntersuchung. Alle 24 Monate (Neuwagen: 36, dann 24).",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    defaultCostCentsMin: 8000,
    defaultCostCentsMax: 15000,
    sortOrder: 140,
  },
  {
    slug: "au_emissions",
    category: "INSPECTION",
    nameEn: "Emissions test (AU)",
    nameDe: "Abgasuntersuchung (AU)",
    descriptionEn: "Emissions inspection, usually combined with HU in Germany.",
    descriptionDe: "Abgasuntersuchung, in DE meist zusammen mit HU.",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    defaultCostCentsMin: 3000,
    defaultCostCentsMax: 6000,
    sortOrder: 150,
  },
  {
    slug: "fuel_additive",
    category: "ADDITIVE",
    nameEn: "Fuel system additive",
    nameDe: "Kraftstoffadditiv",
    descriptionEn: "Diesel/petrol system cleaner additive. Typical: every 5,000 km or 6 months.",
    descriptionDe: "Kraftstoff-Systemreiniger. Typisch: alle 5.000 km oder 6 Monate.",
    defaultIntervalKm: 5000,
    defaultIntervalMonths: 6,
    defaultCostCentsMin: 1500,
    defaultCostCentsMax: 4000,
    sortOrder: 160,
  },
  {
    slug: "adblue",
    category: "ADDITIVE",
    nameEn: "AdBlue / DEF refill",
    nameDe: "AdBlue auffüllen",
    descriptionEn: "Refill diesel exhaust fluid. Consumption varies; check every 10,000 km.",
    descriptionDe: "AdBlue auffüllen. Verbrauch variiert; alle 10.000 km prüfen.",
    defaultIntervalKm: 10000,
    defaultIntervalMonths: 6,
    defaultCostCentsMin: 1500,
    defaultCostCentsMax: 5000,
    sortOrder: 170,
  },
  {
    slug: "wiper_blades",
    category: "OTHER",
    nameEn: "Wiper blades",
    nameDe: "Scheibenwischer",
    descriptionEn: "Replace front/rear wiper blades. Typical: every 12 months.",
    descriptionDe: "Scheibenwischerblätter wechseln. Typisch: alle 12 Monate.",
    defaultIntervalKm: null,
    defaultIntervalMonths: 12,
    defaultCostCentsMin: 2500,
    defaultCostCentsMax: 6000,
    sortOrder: 180,
  },
  {
    slug: "battery_check",
    category: "OTHER",
    nameEn: "Battery check",
    nameDe: "Batterie prüfen",
    descriptionEn: "Test starter battery and terminals. Typical: every 12 months.",
    descriptionDe: "Starterbatterie und Pole prüfen. Typisch: alle 12 Monate.",
    defaultIntervalKm: null,
    defaultIntervalMonths: 12,
    defaultCostCentsMin: 0,
    defaultCostCentsMax: 5000,
    sortOrder: 190,
  },
];
